pts_sylius_order_batch:
  driver: doctrine/orm
  resources:
    batch:
      classes:
        model: PTS\SyliusOrderBatchPlugin\Entity\Batch
    filter:
      classes:
        model: PTS\SyliusOrderBatchPlugin\Entity\Filter
sylius_resource:
  resources:
    app.filter:
      driver: doctrine/orm
      classes:
        model: PTS\SyliusOrderBatchPlugin\Entity\Filter
        repository: PTS\SyliusOrderBatchPlugin\Repository\FilterRepository
        form: PTS\SyliusOrderBatchPlugin\Form\Type\FilterType
    app.batch:
      driver: doctrine/orm
      classes:
        model: PTS\SyliusOrderBatchPlugin\Entity\Batch
        repository: PTS\SyliusOrderBatchPlugin\Repository\BatchRepository
        form: PTS\SyliusOrderBatchPlugin\Form\Type\BatchType
    app.shippingBatch:
      driver: doctrine/orm
      classes:
        model: PTS\SyliusOrderBatchPlugin\Entity\Batch
        repository: PTS\SyliusOrderBatchPlugin\Repository\BatchRepository
        form: PTS\SyliusOrderBatchPlugin\Form\Type\BatchType
sylius_order:
  resources:
    order:
      classes:
        model: Sylius\Component\Core\Model\Order
        repository: PTS\SyliusOrderBatchPlugin\Repository\OrderRepository
        controller: PTS\SyliusOrderBatchPlugin\Controller\OrderController