imports:
  - { resource: "services/filters.yml" }
  - { resource: "services/fixtures.yml" }

services:
  pts_sylius_order_batch_plugin.batch.manager:
    class: 'PTS\SyliusOrderBatchPlugin\Service\BatchManager'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@pts_sylius_order_batch_plugin.form.error.extractor'
      - '@form.factory'
      - '@sm.factory'
      - '@event_dispatcher'
    public: true

  pts_sylius_order_batch_plugin.form.error.extractor:
    public: true
    class: 'PTS\SyliusOrderBatchPlugin\Service\FormErrorExtractor'

  pts_sylius_order_batch_plugin.paginator.manager:
    class: 'PTS\SyliusOrderBatchPlugin\Service\PaginatorManager'
    public: true

  pts_sylius_order_batch_plugin.filter.manager:
    class: 'PTS\SyliusOrderBatchPlugin\Service\FilterManager'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@form.factory'
      - '@jms_serializer.serializer'
      - '@pts_sylius_order_batch_plugin.form.error.extractor'
    public: true

  pts_sylius_order_batch_plugin.listener.admin.menu_builder:
    class: 'PTS\SyliusOrderBatchPlugin\Menu\AdminMenuListener'
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

  app.file_exporting.manager:
    class: 'PTS\SyliusOrderBatchPlugin\Service\FilesExportingService'
    public: true

  app.extension.calculate_quantity:
    class: 'PTS\SyliusOrderBatchPlugin\Extension\OrderItemQuantityExtension'
    tags:
      - 'twig.extension'
  app.form.error.extractor:
    class: 'PTS\SyliusOrderBatchPlugin\Service\FormErrorExtractor'
    public: true
  sylius.resource_controller.resources_resolver.grid_aware:
    class: 'PTS\SyliusOrderBatchPlugin\Service\Overrides\ResourcesResolver'
    decorates: sylius.resource_controller.resources_resolver
    decoration_priority: 256
    arguments:
      - '@sylius.resource_controller.resources_resolver.grid_aware.inner'
      - '@sylius.grid.provider'
      - '@sylius.grid.resource_view_factory'
      - '@pts_sylius_order_batch_plugin.filter.manager'
  sylius.grid.resource_view_factory:
    class: 'PTS\SyliusOrderBatchPlugin\Service\Overrides\ResourceGridViewFactory'
    arguments:
      - '@sylius.grid.data_provider'
      - '@sylius.resource_controller.parameters_parser'
      - '@pts_sylius_order_batch_plugin.filter.manager'
    public: true
  sylius.grid.filters_applicator:
    class: 'PTS\SyliusOrderBatchPlugin\Service\Overrides\FiltersApplicator'
    arguments:
      - '@sylius.registry.grid_filter'
      - '@sylius.grid.filters_criteria_resolver'
    public: true
  pts_sylius_order_batch_plugin.batch_action:
    class: 'PTS\SyliusOrderBatchPlugin\Batch\BatchAction'
    arguments:
      - '@doctrine.orm.entity_manager'
    public: true

